server:
  port: 9092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/comfortable_walk_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true

  radar:
    radar-url: http://weather.rshu.ru/radar/data/
    image-uri-prefix: P_100_26061_
    image-uri-postfix: _MRL

google:
  api:
    key: "AIzaSyBw3Bcepmq4q_VtqIohTNDBHPJnMiNw9yY"
    distance-key: "AIzaSyDsx7KAWwgcWwWdvaVbjLRfWwnqrqoShN0"

logging:
  file: data_collector.log
