server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/netcrackers
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    generate-ddl: true