server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/hellodb
    username: app_test
    password: testpass
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true