server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/comfortable_walk_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.jdbc.lob.non_contextual_creation: true
    show-sql: true

algorithm:
  maxAllowableIncrease: 1.5
  minDistBetweenStartEnd: 100
  scale: 20
  maxCountOfWaypoints: 21
  distanceType: CHEBYSHEVA
  normalFactorH: 2
  normalFactorG: 1
  weatherFieldFactor: 1
  placesFieldFactor: -1
  routeFieldFactor: -0.4
  maxIterationsNum: 10000
  ApiKey: "AIzaSyDsx7KAWwgcWwWdvaVbjLRfWwnqrqoShN0"

logging:
  file: algorithm.log